---
version: '3'

volumes:
  gogs-data:
  mariadb-data:
  drone-data:

services:
  traefik:
    restart: always
    image: traefik:1.2.0
    depends_on: [ gogs, drone-server ]
    ports:
      - '8081:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gogs:
    restart: always
    image: gogs/gogs:0.10.18
    depends_on: [ mariadb-gogs ]
    ports:
      - '2222:22'
    volumes:
      - gogs-data:/data

  mariadb-gogs:
    restart: always
    image: mariadb:10.1.22
    environment:
      - MYSQL_DATABASE=gogs
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=gogs
    volumes:
      - mariadb-data:/var/lib/mysql

  drone-server:
    image: drone/drone:0.6
    volumes:
      - drone-data:/var/lib/drone
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SECRET=drone
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000

  drone-agent:
    image: drone/drone:0.6
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=drone
