---
version: '3'

networks:
  ci-network:
    external:
      name: ci_ci-network

volumes:
  gogs-data:
  mariadb-data:
  drone-data:
  registry-data:

services:
  gogs:
    image: gogs/gogs:0.10.18
    depends_on: [ mariadb-gogs ]
    volumes:
      - gogs-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:gogs.${DOMAIN}"
    networks:
      - ci-network

  mariadb-gogs:
    image: mariadb:10.1.22
    environment:
      - MYSQL_DATABASE=gogs
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=gogs
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - ci-network

  drone-server:
    image: ael/drone
    volumes:
      - drone-data:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=ael
      - DRONE_SECRET=drone
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000
      - EXTERNAL_NETWORKS=ci_ci-network
    labels:
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:drone.${DOMAIN}"
    networks:
      - ci-network

  drone-agent:
    image: ael/drone
    command: agent
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=drone
    networks:
      - ci-network

  registry:
    image: registry:2.6
    volumes:
      - registry-data:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - ci-network

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - "ENV_DOCKER_REGISTRY_HOST=registry"
      - "ENV_DOCKER_REGISTRY_PORT=5000"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:registry-ui.${DOMAIN}"
    networks:
      - ci-network
