---
version: '3'

networks:
  ci-network:
    external:
      name: ci_ci-network
  monitoring-network:
    external:
      name: monitoring_monitoring-network

services:
  traefik:
    image: traefik:1.2.0
    command: 
      - --web 
      - --docker 
      - --docker.watch 
      - --docker.swarmmode 
      - --docker.domain=traefik
      - --logLevel=DEBUG 
      - --docker.exposedbydefault=false
    ports:
      - '8081:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - ci-network
      - monitoring-network
