---
version: '3'

networks:
  monitoring-network:
    external:
      name: monitoring_monitoring-network

volumes:
  prometheus-data:
  grafana-data:
#  elasticsearch-data:

services:
  prometheus:
    image: prom/prometheus:v1.5.2
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "-alertmanager.url=http://alertmanager:9093"
      - "-config.file=/etc/prometheus/prometheus.yml"
    deploy:
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.enable=true"
        - "traefik.port=9090"
        - "traefik.frontend.rule=Host:prometheus.${DOMAIN}"
    networks:
      - monitoring-network

  alertmanager:
    image: prom/alertmanager:v0.5.1
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:4.2.0
    depends_on: [ prometheus ]
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:grafana.${DOMAIN}"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=grafana"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    networks:
      - monitoring-network

#  elasticsearch:
#    image: elasticsearch:5.2
#    networks:
#      - monitoring-network
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#
#  kibana:
#    image: kibana:5.2
#    depends_on: [ elasticsearch ]
#    environment:
#      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
#    deploy:
#      labels:
#        - "traefik.enable=true"
#        - "traefik.port=5601"
#        - "traefik.frontend.rule=Host:kibana.${DOMAIN}"
#    networks:
#      - monitoring-network
