---
version: '3'

networks:
  monitoring-network:
    external:
      name: monitoring_monitoring-network

volumes:
  prometheus-data:
  grafana-data:
#  elasticsearch-data:

services:
  prometheus:
    image: prom/prometheus:v1.5.2
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "-alertmanager.url=http://alertmanager:9093"
      - "-config.file=/etc/prometheus/prometheus.yml"
    labels:
      - "traefik.enable=true"
      - "traefik.port=9090"
      - "traefik.frontend.rule=Host:prometheus.${DOMAIN}"
    networks:
      - monitoring-network

#  node-exporter:
#    image: prom/node-exporter:v0.14.0
#    volumes:
#      - "/proc:/host/proc"
#      - "/sys:/host/sys"
#      - "/etc/hostname:/etc/host_hostname"
#    command:
#      - "-collector.procfs /host/proc"
#      - "-collector.sysfs /host/sys"
#      - "-collector.filesystem.ignored-mount-points \"^/(sys|proc|dev|host|etc)($|/)\""
#    networks:
#      - monitoring-network

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.4.0
    volumes:
      - "./backbox.yml:/config/"
    networks:
      - monitoring-network

  alertmanager:
    image: prom/alertmanager:v0.5.1
    volumes:
      - ./alertmanager.yml:/alertmanager.yml
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:4.2.0
    depends_on: [ prometheus ]
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - "GF_AUTH_BASIC_ENABLED=false"
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:grafana.${DOMAIN}"
    networks:
      - monitoring-network

#  elasticsearch:
#    image: elasticsearch:5.2
#    networks:
#      - monitoring-network
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#
#  kibana:
#    image: kibana:5.2
#    depends_on: [ elasticsearch ]
#    environment:
#      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.port=5601"
#      - "traefik.frontend.rule=Host:kibana.${DOMAIN}"
#    networks:
#      - monitoring-network

#  metricbeat:
#    image: athieriot/metricbeat:5.2.0
#    depends_on: [ elasticsearch ]
#    pid: host
#    volumes:
#      - "/proc:/hostfs/proc:ro"
#      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
#      - "/:/hostfs:ro"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "./metricbeat.yml:/metricbeat/metricbeat.yml"
#    command:
#      - "-system.hostfs=/hostfs"
#    networks:
#      - monitoring-network
#    deploy:
#      mode: global
