global:
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 15s
    dns_sd_configs:
      - names: [ 'tasks.node-exporter' ]
        type: 'A'
        port: 9100
  - job_name: 'cadvisor'
    scrape_interval: 15s
    dns_sd_configs:
      - names: [ 'tasks.cadvisor' ]
        type: 'A'
        port: 8080
