# -*- mode: ruby -*-
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

require 'yaml'

servers = YAML.load_file('nodes.yml')
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.hostname = servers["name"]
      srv.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "hosts.inv"
        ansible.limit = "localhost"
      end
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
      end
    end
  end
end
